package cc.aerial.client.screen.tabs.scripts;

/** Turns a visual {@link ScriptModel} into runnable JavaScript for the existing Nashorn host. */
public final class ScriptCodeGen {
    private ScriptCodeGen() {
    }

    public static String toJs(ScriptModel model) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by the Aerial Script Constructor. Edit in the Advanced tab if you like.\n");
        sb.append("var __m = modules.registerModule(")
                .append(jsString(model.name)).append(", ")
                .append(jsString(model.description)).append(", \"SCRIPTS\");\n");
        sb.append("__m.").append(model.trigger.template).append("(function() {\n");

        if (!model.conditions.isEmpty()) {
            sb.append("    if (!(");
            for (int i = 0; i < model.conditions.size(); i++) {
                if (i > 0) {
                    sb.append(" && ");
                }
                sb.append(fill(model.conditions.get(i)));
            }
            sb.append(")) return;\n");
        }

        for (ScriptModel.Block action : model.actions) {
            sb.append("    ").append(fill(action)).append("\n");
        }

        sb.append("});\n");
        sb.append("utils.log(").append(jsString(model.name + " loaded")).append(");\n");
        return sb.toString();
    }

    /** Fills a block's template with code-formatted parameter values. */
    private static String fill(ScriptModel.Block block) {
        String out = block.def.template;
        for (int i = 0; i < block.def.params.size(); i++) {
            BlockDef.Param param = block.def.params.get(i);
            String raw = block.values[i] != null ? block.values[i] : param.defaultValue();
            String formatted = param.type() == BlockDef.ParamType.TEXT ? jsString(raw) : number(raw);
            out = out.replace("{" + i + "}", formatted);
        }
        return out;
    }

    /** Fills a block's label with the raw parameter values for display in the UI. */
    public static String label(BlockDef def, String[] values) {
        String out = def.label;
        for (int i = 0; i < def.params.size(); i++) {
            String raw = (values != null && i < values.length && values[i] != null)
                    ? values[i] : def.params.get(i).defaultValue();
            out = out.replace("{" + i + "}", raw);
        }
        return out;
    }

    private static String number(String raw) {
        try {
            double value = Double.parseDouble(raw.trim());
            if (value == Math.floor(value) && !Double.isInfinite(value)) {
                return Long.toString((long) value);
            }
            return Double.toString(value);
        } catch (NumberFormatException e) {
            return "0";
        }
    }

    private static String jsString(String raw) {
        StringBuilder sb = new StringBuilder("\"");
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> sb.append(c);
            }
        }
        return sb.append("\"").toString();
    }
}
